// app/layout.js or app/layout.tsx (depending on your setup)
import './globals.css';
import ThemeProvider from '@/components/ThemeContext';
import Footer from '@/components/Footer';
import { Raleway } from 'next/font/google';

// Load Google Fonts using next/font for better performance
const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap', // This ensures a fallback font is shown while the web font is loading
});

export const metadata = {
  title: 'Aneesh Patne - Professional Portfolio',
  description: 'Masters student with a strong foundation in Full Stack Web Development & Data Structures and Algorithms.',
};

export default function RootLayout({ children }) {
  const jsonLdData = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    mainEntity: {
      '@type': 'Person',
      name: 'Aneesh Patne',
      url: 'https://www.aneeshpatne.com',
      image: 'https://www.aneeshpatne.com/assets/img/aneesh.png',
      sameAs: [
        'https://www.linkedin.com/in/aneeshpatne',
        'https://github.com/aneeshpatne',
      ],
      description: 'Aneesh Patne is an engineer with expertise in full stack web development, data structures, and algorithms.',
      alumniOf: {
        '@type': 'CollegeOrUniversity',
        name: 'Veermata Jijabai Technological University',
      },
    },
  };

  return (
    <html lang="en" className={raleway.className}>
      <head>
        {/* Inline script to handle theme setting before rendering */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                if (theme === 'LightMode') {
                  document.body.classList.add('LightMode');
                } else {
                  document.body.classList.remove('LightMode');
                }
                document.body.setAttribute('data-theme-set', 'true'); // Ensure the body is shown after theme is applied
              })();
            `,
          }}
        />
        <meta property="og:title" content="Aneesh Patne - Professional Portfolio" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.aneeshpatne.com/" />
        <meta property="og:image" content="https://www.aneeshpatne.com/assets/img/header.png" />
        <meta property="og:description" content="Masters student with a strong foundation in Full Stack Web Development & Data Structures and Algorithms." />
        <meta property="og:site_name" content="Aneesh Patne - Professional Portfolio" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@aneeshpatne" />
        <meta name="twitter:title" content="Aneesh Patne - Professional Portfolio" />
        <meta name="twitter:description" content="Generated by create next app" />
        <meta name="twitter:image" content="https://www.aneeshpatne.com/assets/img/aneesh.png" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdData) }} />
      </head>
      <body>
        <ThemeProvider>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
