import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import "../components/style/header.css";
import ThemeProvider from "@/components/ThemeContext";
import Footer from "@/components/Footer";

//Noto_Sans
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "Aneesh Patne - Professional Portfolio",
  description:
    "Masters student with a strong foundation in Full Stack Web Development & Data Structures and Algorithms.",
  link: [
    {
      rel: "preload",
      href: "../components/style/header.css",
      as: "style",
    },
  ],
};

export default function RootLayout({ children }) {
  const jsonLdData = {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    mainEntity: {
      "@type": "Person",
      name: "Aneesh Patne",
      url: "https://www.aneeshpatne.com",
      image: "https://www.aneeshpatne.com/assets/img/aneesh.png",
      sameAs: [
        "https://www.linkedin.com/in/aneeshpatne",
        "https://github.com/aneeshpatne",
      ],
      description:
        "Aneesh Patne is a engineer with expertise in full stack web development, data structures, and algorithms.",
      alumniOf: {
        "@type": "CollegeOrUniversity",
        name: "Veermata Jijabai Technological University",
      },
    },
  };

  return (
    <html lang="en" className={raleway.className}>
      <head>
        <meta
          property="og:title"
          content="Aneesh Patne - Professional Portfolio"
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.aneeshpatne.com/" />
        <meta
          property="og:image"
          content="https://www.aneeshpatne.com/assets/img/header.png"
        />
        <meta
          property="og:description"
          content="Masters student with a strong foundation in Full Stack Web Development & Data Structures and Algorithms."
        />
        <meta
          property="og:site_name"
          content="Aneesh Patne - Professional Portfolio"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@aneeshpatne" />
        <meta
          name="twitter:title"
          content="Aneesh Patne - Professional Portfolio"
        />
        <meta
          name="twitter:description"
          content="Generated by create next app"
        />
        <meta
          name="twitter:image"
          content="https://www.aneeshpatne.com/assets/img/aneesh.png"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdData) }}
        ></script>
      </head>
      <body>
        <script>0</script>
        <ThemeProvider>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
